[project]
site_name = "Git is my lab book"
site_url = "https://git-is-my-lab-book.net/"
repo_url = "https://github.com/robmoss/git-is-my-lab-book"
edit_uri = "edit/master/docs/"
extra_css = [
  "extra/asciinema-player.css",
  "extra/asciinema-theme-gimlb.css",
  "extra/larger-admonitions.css"
]
extra_javascript = [
  "extra/asciinema-player.min.js",
  "extra/wrapper.js"
]
# NOTE: Zensical does not (yet) support exclude_docs.
# See https://zensical.org/docs/setup/basics/#unsupported-settings for more.
# Ignore TOML scripts for generating asciinema recordings.
# exclude_docs = [
#   "*.toml",
#   "*.yaml",
# ]

nav = [
  { "Introduction" = [
    "README.md",
    { "How to contribute" = "how-to-contribute.md" },
    { "Contributors" = "contributors.md" },
  ]},
  { "Orientation" = [
    "orientation/README.md",
  ]},
  { "Topical guides" = [
    "guides/README.md",
    { "Learning objectives" = "guides/learning-objectives.md" },
    { "Prerequisites" = "guides/prerequisites.md" },
    { "1. Version control concepts" = [
      "guides/version-control/README.md",
      { "What is version control?" = "guides/version-control/what-is-version-control.md" },
      { "What is a repository?" = "guides/version-control/what-is-a-repository.md" },
      { "What is a commit?" = "guides/version-control/what-is-a-commit.md" },
      { "What should I commit?" = "guides/version-control/what-should-I-commit.md" },
      { "How do I write a commit message?" = "guides/version-control/how-do-I-write-a-commit-message.md" },
      { "What is a tag?" = "guides/version-control/what-is-a-tag.md" },
      { "What is a branch?" = "guides/version-control/what-is-a-branch.md" },
      { "What is a merge conflict?" = "guides/version-control/what-is-a-merge-conflict.md" },
      { "Exercise: using version control" = "guides/version-control/exercise-using-version-control.md" },
    ]},
    { "2. Effective use of git" = [
      "guides/using-git/README.md",
      { "Graphical Git clients" = "guides/using-git/graphical-git-clients.md" },
      { "First-time Git setup" = "guides/using-git/first-time-git-setup.md" },
      { "Choosing your Git editor" = "guides/using-git/choosing-your-git-editor.md" },
      { "Creating a repository" = "guides/using-git/creating-a-repository.md" },
      { "Cloning an existing repository" = "guides/using-git/cloning-an-existing-repository.md" },
      { "How to structure a repository" = "guides/using-git/how-to-structure-a-repository.md" },
      { "Choosing a license" = "guides/using-git/choosing-a-license.md" },
      { "Creating a commit" = "guides/using-git/creating-a-commit.md" },
      { "Creating a remote repository" = "guides/using-git/creating-a-remote-repository.md" },
      { "Pushing and pulling commits" = "guides/using-git/pushing-and-pulling-commits.md" },
      { "How to ignore certain files" = "guides/using-git/how-to-ignore-certain-files.md" },
      { "How to create and use tags" = "guides/using-git/how-to-create-and-use-tags.md" },
      { "Inspecting your history" = "guides/using-git/inspecting-your-history.md" },
      { "Where did this line come from?" = "guides/using-git/where-did-this-line-come-from.md" },
      { "Where did this problem come from?" = "guides/using-git/where-did-this-problem-come-from.md" },
      { "How to use branches?" = "guides/using-git/how-to-use-branches.md" },
      { "How to resolve merge conflicts?" = "guides/using-git/how-to-resolve-merge-conflicts.md" },
      { "Exercise: create a local repository" = "guides/using-git/exercise-create-a-local-repository.md" },
      { "Exercise: use a remote repository" = "guides/using-git/exercise-use-a-remote-repository.md" },
      { "Exercise: resolve a merge conflict" = "guides/using-git/exercise-resolve-a-merge-conflict.md" },
    ]},
    { "3. Collaborating" = [
      "guides/collaborating/README.md",
      { "Collaborating on code" = "guides/collaborating/collaborating-on-code.md" },
      { "Collaborating on a paper" = "guides/collaborating/collaborating-on-a-paper.md" },
      { "Sharing a repository" = "guides/collaborating/sharing-a-repository.md" },
      { "Sharing a branch" = "guides/collaborating/sharing-a-branch.md" },
      { "Merge/Pull requests" = "guides/collaborating/merge-pull-requests.md" },
      { "An example pull request" = "guides/collaborating/an-example-pull-request.md" },
      { "Peer code review" = "guides/collaborating/peer-code-review.md" },
      { "Coding style guides" = "guides/collaborating/coding-style-guides.md" },
      { "Continuous integration" = "guides/collaborating/continuous-integration.md" },
    ]},
    { "4. Project structure" = [
      "guides/project-structure/README.md",
      { "Define your workflow" = "guides/project-structure/workflow.md" },
      { "Automate common tasks" = "guides/project-structure/automating-tasks.md" },
      { "Explain how it works" = "guides/project-structure/explain-how-it-works.md" },
      { "Exercise: what works for you?" = "guides/project-structure/exercise-what-works-for-you.md" },
      { "Exercise: a good README" = "guides/project-structure/exercise-a-good-readme.md" },
    ]},
    { "5. Writing code" = [
      "guides/writing-code/README.md",
      { "How we learn to write code" = "guides/writing-code/how-we-learn-to-write-code.md" },
      { "Cohesion and coupling" = "guides/writing-code/cohesion-coupling.md" },
      { "Behave nicely" = "guides/writing-code/behave-nicely.md" },
      { "Coding advice" = "guides/writing-code/coding-advice.md" },
      { "Create packages" = "guides/writing-code/create-packages.md" },
      { "Check your code" = "guides/writing-code/check-your-code.md" },
      { "Format your code" = "guides/writing-code/format-your-code.md" },
      { "Document your code" = "guides/writing-code/document-your-code.md" },
      { "Exercise: seek feedback" = "guides/writing-code/exercise-seek-feedback.md" },
    ]},
    { "6. Reproducibility" = [
      "guides/reproducibility/README.md",
      { "What is reproducible research?" = "guides/reproducibility/what-is-reproducible-research.md" },
    ]},
    { "7. Testing" = [
      "guides/testing/README.md",
    ]},
    { "8. Cloud and HPC platforms" = [
      "guides/high-performance-computing/README.md",
    ]},
    { "Useful resources" = "guides/resources.md" },
  ]},
  { "Community" = [
    "community/README.md",
    { Meetings = [
      "community/meetings/README.md",
      { "14 November 2024" = "community/meetings/2024-11-14.md" },
      { "10 October 2024" = "community/meetings/2024-10-10.md" },
      { "12 September 2024" = "community/meetings/2024-09-12.md" },
      { "8 August 2024" = "community/meetings/2024-08-08.md" },
      { "11 July 2024" = "community/meetings/2024-07-11.md" },
      { "13 June 2024" = "community/meetings/2024-06-13.md" },
      { "9 May 2024" = "community/meetings/2024-05-09.md" },
      { "11 April 2024" = "community/meetings/2024-04-11.md" },
      { "19 February 2024" = "community/meetings/2024-02-19.md" },
      { "18 October 2023" = "community/meetings/2023-10-18.md" },
      { "15 August 2023" = "community/meetings/2023-08-15.md" },
      { "13 June 2023" = "community/meetings/2023-06-13.md" },
      { "17 April 2023" = "community/meetings/2023-04-17.md" },
    ]},
    { "Case studies" = [
      "community/case-studies/README.md",
      { "Fixing a bug in pypfilt" = "community/case-studies/moss-pypfilt-earlier-states.md" },
      { "Incorrect data in a pre-print figure" = "community/case-studies/moss-incorrect-data-pre-print.md" },
      { "Pen and paper version control" = "community/case-studies/campbell-pen-and-paper-version-control.md" },
    ]},
    { "Training events" = [
      "community/training/README.md",
      { "Introduction to Debugging" = [
        "community/training/debugging/README.md",
        { "Learning objectives" = "community/training/debugging/learning-objectives.md" },
        { "What is debugging?" = "community/training/debugging/what-is-debugging.md" },
        { "Understanding error messages" = "community/training/debugging/understanding-error-messages.md" },
        { "Why are debuggers useful?" = "community/training/debugging/why-are-debuggers-useful.md" },
        { "Using a debugger" = "community/training/debugging/using-a-debugger.md" },
        { "When something fails" = "community/training/debugging/when-something-fails.md" },
        { "Real-world stories" = "community/training/debugging/real-world-stories.md" },
        { "Example: Square numbers" = "community/training/debugging/example-square-numbers.md" },
        { "Exercise: Perfect numbers" = "community/training/debugging/exercise-perfect-numbers.md" },
        { "Exercise: Python vs R" = "community/training/debugging/exercise-python-vs-r.md" },
        { "Building your skills" = "community/training/debugging/building-your-skills.md" },
        { "Debugging manifesto" = "community/training/debugging/manifesto.md" },
        { "Resources" = "community/training/debugging/resources.md" },
        { "Exercise solutions" = "community/training/debugging/solutions.md" },
        { "Acknowledgements" = "community/training/debugging/acknowledgements.md" },
      ]},
    ]}
  ]},
]

[project.theme]
name = "material"
favicon = "logo.png"
logo = "logo.svg"
# Retain the Material for MkDocs theme for now.
# See https://zensical.org/docs/setup/basics/ for further details.
variant = "classic"
features = [
  # Navigation settings
  "navigation.footer",
  "navigation.indexes",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "toc.follow",
  "toc.integrate",
  # See "Adding a git repository"
  "content.action.edit",
  # Code block settings
  "content.code.copy",
  "content.code.select",
  # Content tab settings
  "content.tabs.link"
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "material/brightness-auto"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "material/brightness-7"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "material/brightness-4"
toggle.name = "Switch to system preference"

[project.markdown_extensions.admonition]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.footnotes]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.emoji]
# We use this to show the "Edit this page" icon on the "How to contribute" page.
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.snippets]
# We use snippets in the "Introduction to Debugging" workshop.
base_path = [
  # Locate snippets relative to the documentation root directory.
  "docs/",
  # Locate snippets in the 2024 debugging workshop directory.
  "docs/community/training/debugging"
]

[project.markdown_extensions.pymdownx.superfences]
# NOTE: we use mermaid diagrams in the "Introduction to Debugging" workshop.
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.toc]
permalink = "Â¶"
